styling-PR
gilberthappi/Bookstore-App pull request #8
Opened 2023-10-13 22:53 UTC by gilberthappi

Apply React best practices and language style guides in code.

2023-10-13 23:29 UTC, joskalenda requested changes
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @gilberthappi , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2NpKgBuUZtXpu/giphy.gif"/> |

### Highlights
✅ ...
✅ ...

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-13 23:29 UTC, joskalenda commented on src/App.js
- [ ] Your design is almost perfect, you have done it at 98%, but see, we are expecting from the student more than that, you are being presented with both image
- ORIGINAL TEMPLATE
I am sure there is no additional color in the background or your green tests as you mentioned
<img width="798" alt="1" src="https://github.com/gilberthappi/Bookstore-App/assets/77843050/5fd5d14c-9ede-4cc4-9d0b-43a07ae1dfa2">

- [ ] Your design

<img width="1279" alt="2" src="https://github.com/gilberthappi/Bookstore-App/assets/77843050/33b07637-e1cd-4db9-9cc4-4396ce3d03e7">

2023-10-14 21:38 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @gilberthappi , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Well done implementing the requested changes. 🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-14 21:38 UTC, ridwanediallo commented on src/style.css
> +  width: 100vw;
- [ **OPTIONAL**] I think your app will look nicer if you remove this fixed width and ensure that the app is centred on the screen as on the template.

2023-10-14 21:51 UTC, merged